### ISSUE TITLE
Restrict context menu to valid component locations

### ISSUE THREAD

**Issue by mvsde** [miyagi-dev/vscode-miyagi#4]
At the moment the explorer context menu is shown for all folders in the workspace. The context menu should be restricted to valid component locations only.

The `components.folder` setting from the miyagi config determines the allowed root folder for components. If `engine.options.namespaces` is set, this option can be used to further define allowed locations.

**Comment by mvsde** [comment]
This is really hard to accomplish with VS Code’s [when clause contexts](https://code.visualstudio.com/api/references/when-clause-contexts) system.

One option would be to save all valid component parents in an array and use the [`in` conditional](https://code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator). This would require keeping track of folder additions/deletions which in turn needs a file system watcher.

**Comment by mgrsskls** [comment]
If this is too difficult to implement, I _think_ the API could at least return the information that the selected directory is not inside `components.folder`. That way we could at least give a hint to the user.
